In [5]:
import pandas

In [6]:
projects_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\projects_raw.csv")
projects_df = pandas.DataFrame(projects_data)
projects_df

    project_id project_code            theme  donor_id  office_id
0            1     PRJ-0001       Protection       7.0          9
1            2     PRJ-0002           Health       6.0          3
2            3     PRJ-0003        Education       8.0          1
3            4     PRJ-0004       Protection       6.0         12
4            5     PRJ-0005    Food Security       5.0          8
5            6     PRJ-0006  Cash Assistance       NaN         10
6            7     PRJ-0007             WASH       2.0         12
7            8     PRJ-0008  Cash Assistance       7.0         12
8            9     PRJ-0009  Cash Assistance       1.0          5
9           10     PRJ-0010        Education       7.0          1
10          11     PRJ-0011  Cash Assistance       5.0          8
11          12     PRJ-0012  Cash Assistance       4.0         13
12          13     PRJ-0013        Education       4.0         11
13          14     PRJ-0014           Health       5.0          2
14          15     PRJ-0015  Cash Assistance       4.0          4
15          16     PRJ-0016    Food Security       4.0          8
16          17     PRJ-0017        Education       8.0          3
17          18     PRJ-0018           Health       2.0          3
18          19     PRJ-0019           Health       8.0         11
19          20     PRJ-0020             WASH       5.0          9
20          21     PRJ-0021       Protection       4.0          8
21          22     PRJ-0022    Food Security       8.0          5
22          23     PRJ-0023  Cash Assistance       7.0          6
23          24     PRJ-0024             WASH       5.0         12
24          25     PRJ-0025    Food Security       5.0         10
25          26     PRJ-0026        Education       2.0         11
26          27     PRJ-0027       Protection       5.0          6
27          28     PRJ-0028       Protection       8.0          2
28          29     PRJ-0029           Health       1.0          7
29          30     PRJ-0030             WASH       5.0          3

In [7]:
projects_df.head()

   project_id project_code          theme  donor_id  office_id
0           1     PRJ-0001     Protection       7.0          9
1           2     PRJ-0002         Health       6.0          3
2           3     PRJ-0003      Education       8.0          1
3           4     PRJ-0004     Protection       6.0         12
4           5     PRJ-0005  Food Security       5.0          8

In [8]:
projects_df.isnull().sum()

project_id      0
project_code    0
theme           0
donor_id        1
office_id       0
dtype: int64

In [9]:
projects_df.duplicated().sum()

np.int64(0)

In [10]:
projects_df.describe().T

            count       mean       std  min   25%   50%    75%   max
project_id   30.0  15.500000  8.803408  1.0  8.25  15.5  22.75  30.0
donor_id     29.0   5.103448  2.127118  1.0  4.00   5.0   7.00   8.0
office_id    30.0   7.166667  3.797307  1.0  3.25   8.0  10.75  13.0

In [11]:
projects_df = projects_df.dropna()

In [12]:
projects_df["theme"] = projects_df["theme"].str.title()

In [14]:
projects_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\projects.csv",index=False)