In [22]:
import pandas

In [23]:
education_data = pandas.read_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\raw\education_services_raw.csv")
education_df = pandas.DataFrame(education_data)
education_df.head()

,education_id,beneficiary_id,school_code,education_level,country,enrollment_date,status
0,1,4604,SCH-063,Primary,South Sudan,2025-03-19,Enrolled
1,2,1542,SCH-071,Secondary,Uganda,2024-07-30,Enrolled
2,3,3310,SCH-028,Vocational,Somalia,2024-09-24,Dropped
3,4,2551,SCH-029,Vocational,Ethiopia,2025-09-17,Dropped
4,5,4478,SCH-009,NaN,Kenya,2024-09-30,Dropped

In [24]:
education_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   education_id     3000 non-null   int64
 1   beneficiary_id   3000 non-null   int64
 2   school_code      3000 non-null   str
 3   education_level  2999 non-null   str
 4   country          3000 non-null   str
 5   enrollment_date  3000 non-null   str
 6   status           2999 non-null   str
dtypes: int64(2), str(5)
memory usage: 164.2 KB

In [25]:
education_df = education_df.dropna()

In [26]:
education_df["enrollment_date"] = pandas.to_datetime(education_df["enrollment_date"],format='mixed', errors='coerce')

In [27]:
education_df["country"].unique()

<StringArray>
['South Sudan', 'Uganda', 'Somalia', 'Ethiopia', 'UGANDA ', 'Kenya']
Length: 6, dtype: str

In [28]:
education_df["country"] = education_df["country"].str.strip()

In [29]:
education_df["country"] = education_df["country"].str.title()

In [30]:
education_df["education_level"].unique()

<StringArray>
['Primary', 'Secondary', 'Vocational', 'Adult Learning']
Length: 4, dtype: str

In [31]:
education_df["status"].unique()

<StringArray>
['Enrolled', 'Dropped', 'Completed']
Length: 3, dtype: str

In [32]:
education_df.duplicated().sum()

np.int64(0)

In [33]:
countries_lookup = {"Kenya" : 1,
                    "Uganda" : 2,
                    "South Sudan" : 3,
                    "Ethiopia" : 4,
                    "Somalia" : 5,
                    "Dr Congo" : 6,
                    "Rwanda" : 7,
                    "Burundi" : 8,
                    "Tanzania" : 9,
                    "Sudan" : 10,}

In [34]:
education_df =  education_df.rename(columns={"country":"country_id"})

In [35]:
education_df["country_id"] = education_df["country_id"].map(countries_lookup)

In [36]:
education_df.head()

,education_id,beneficiary_id,school_code,education_level,country_id,enrollment_date,status
0,1,4604,SCH-063,Primary,3,2025-03-19,Enrolled
1,2,1542,SCH-071,Secondary,2,2024-07-30,Enrolled
2,3,3310,SCH-028,Vocational,5,2024-09-24,Dropped
3,4,2551,SCH-029,Vocational,4,2025-09-17,Dropped
5,6,4039,SCH-019,Adult Learning,3,2025-08-17,Dropped

In [37]:
education_df.describe().T

,count,mean,min,25%,50%,75%,max,std
education_id,2998.0,1501.493996,1.0,752.25,1501.5,2250.75,3000.0,865.602744
beneficiary_id,2998.0,2476.708806,1.0,1232.25,2430.5,3754.0,5000.0,1449.474182
country_id,2998.0,3.003336,1.0,2.0,3.0,4.0,5.0,1.40972
enrollment_date,2998,2025-07-13 11:23:00.920613,2024-07-19 00:00:00,2025-01-13 00:00:00,2025-07-07 00:00:00,2026-01-08 00:00:00,2026-07-19 00:00:00,NaN

In [38]:
education_df.to_csv(r"C:\Users\ELITEX21012G2\Desktop\REFUGEES PROJECT\data\clean\education_services.csv", index=False)